### PR TITLE
Added element_count_is method

### PR DESCRIPTION
**Pull request by zoffixznet**
This allows for testing for whether the page contains the expected number of elements, based on the provided selector. You can either test for the exact number, or more/less than the specified number.

### CODE REVIEW

**Comment by jberger** [comment]
Without commenting on the utility or implementation of this method, remember that "its not a feature without tests and documentation". I see documentation but not tests.

**Comment by jberger** [comment]
Also, rather than parsing the test on your own and turning it into an `ok` test, why not use `cmp_ok`?

**Comment by jhthorsen** [comment]
I don't like the name. ```element_count``` sounds like something that returns a number, instead of comparing. Maybe rather ```number_of_elements_is```. (Probably a bit too long though)

I'm no sure if i see why you would need ```cmp_ok```, instead of simply ```is```

Also, I'm still not sure if I'm positive to the addition. (I'm not negative, just haven't decided)

**Comment by jberger** [comment]
`cmp_ok` lets you test `<=`, `==`, `>` or the like, and gives descriptive feedback on failure (rather than just pass/fail of `ok`)

**Comment by zoffixznet** [comment]
How about `element_count_is` ?

**Comment by jberger** [comment]
I would personally expect it to be something more like `selector_count_is`

**Comment by jberger** [comment]
put it a different way, all of the `element_` tests are testing a specific single element. This test method would be testing the result of a query returning a collection, and indeed testing the collection not the element.

**Comment by zoffixznet** [comment]
`selector_count_is` is very confusing to me. I'm certainly not counting selectors (CSS), but elements (HTML) my selector matches. The fact that I'm using CSS selectors to tell the test what to count is secondary to what the purpose of the test is.

I've updated the PR to include tests. Please check and offer suggestions.

**Comment by jberger** [comment]
why parse out the `$operator` part of the test, why not just accept an `$operator` argument?

**Comment by zoffixznet** [comment]
The `==`, `<`, and `>` operators cover all the use cases (so anything else `cmp_ok` accepts isn't needed). The `==` is a sensible default. Since test description is an optional argument, I don't see another good way to have an optional operator argument as well, other than simply parse it out.

**Comment by jhthorsen** [comment]
I don't like ```selector_count_is```. I'm also unsure about using ```cmp_ok```, while having the test method end with "_is". In which case do you need the operator, which require ```cmp_ok```, instead of simply ```is```?

**Comment by kraih** [comment]
I also don't like any of the proposed method names, perhaps something like `elements_exist`?

**Comment by jhthorsen** [comment]
I think ```elements_exist``` sounds like "give this method multiple selectors, and only succeed if all exists". I rather like something like ```n_elements_exists", but "n_" is not very understandable.

**Comment by kraih** [comment]
@jhthorsen Disagree, ` $t->elements_exist('.field-with-error', '>', 6)` looks fine to me.

**Comment by kraih** [comment]
@jhthorsen But i guess you meant `$t->elements_exist('.field-with-error', '>6')`, which does indeed look too similar to another selector.

**Comment by kraih** [comment]
There is a similar method in [Casper.js](http://casperjs.readthedocs.org/en/latest/modules/tester.html#assertelementcount), think i would be fine with the name `element_count_is` if there was no support for ranges.

**Comment by zoffixznet** [comment]
Updated to remove ranges

**Comment by jhthorsen** [comment]
:+1: from me now.

**Comment by jberger** [comment]
I'm happy with the name `element_count_is`. While I was supportive of ranges via `cmp_ok` I think @kraih 's suggestion that there aren't many great cases for tests where an exact value isn't known but a range is. I'm now :+1: on implementation and leaning :+1: on inclusion.

**Comment by kraih** [comment]
Thanks, applied. :+1:

**Pull request merged**
