### PR TITLE
Add ability to track name of the executable script by not resolving symlinks

### PR DESCRIPTION
**Pull request by cono**
Change Cwd::abs_path to File::Spec->rel2abs

### CODE REVIEW

**Comment by cono** [comment]
Started conversation here:
https://groups.google.com/forum/#!topic/mojolicious/OQEH0Aisouo

Sebastian, would you mind to place label: work in progress
I'm willing to cover this change with some tests and add some words in documentation.
But its 2:47am over here :) So gonna do it a bit later.

**Comment by kraih** [comment]
Please don't open unfinished pull requests.

**Comment by cono** [comment]
Sorry, I thought its a common practice to make work visible earlier by labeling it "work in progress": #737

**Comment by kraih** [comment]
For the record, i've actually tried this patch and it didn't pass all tests on OS X.

**Comment by cono** [comment]
@kraih would you mind to post prove result?

**Comment by kraih** [comment]
The 6.06 release actually used `rel2abs` instead of `abs_path` in some cases, and the bug reports have started coming in. https://github.com/kraih/mojo/issues/779

**Comment by kraih** [comment]
A few more.
http://www.cpantesters.org/cpan/report/e9ce217a-6c9d-1014-bc1b-836f56a2bf19
http://www.cpantesters.org/cpan/report/cd867c2d-6bf6-1014-9b4e-4eb7ae217b3d
http://www.cpantesters.org/cpan/report/ada72587-6bf7-1014-95c5-84ab24fcbee8
http://www.cpantesters.org/cpan/report/c6dd4dd1-6bf3-1014-9398-3af5bc74cf01

**Comment by cono** [comment]
@kraih my first intention was to fix daemon.t in a way:

+  rel2abs($path), 'right script name');

Which calls "canonpath" inside of it. But just removed it :(

As for the current issues, only daemon.t is failing and imho the issue as itself not critical.

p.s. its a pity that you are reverting it :(

**Comment by kraih** [comment]
Failing installations for a large number of our users is a very critical issue!

**Comment by kraih** [comment]
We have decided that this is not worth doing more experiments, and the change has therefore been reverted. https://github.com/kraih/mojo/commit/693a3cf2ba8288cca89a45781dc9b33406251bde

**Comment by cono** [comment]
Got it.
Thanks for the try.

**Pull request closed without merging**
