### PR TITLE
callback shortcut

### PR DESCRIPTION
**Pull request by mche**
Hi!

### CODE REVIEW

**Comment by marcusramberg** [comment]
This pull request needs an actual description to be considered.

**Comment by mche** [comment]
> an actual description

`$r->to(sub {...}) `

is same as

`$r->to(cb=>sub {...}) `

>  tests

Ok

**Comment by mche** [comment]
huge amount tests in /t!
suggest me where to place test callback action.

**Comment by jberger** [comment]
Why wouldn't you just use the hybrid route approach at this point? `$r->any('/path' => sub { ... })`

**Comment by kraih** [comment]
👎 from me, since we already have enough alternatives.

**Comment by jberger** [comment]
without a compelling reason not to use the hybrid routes I mentioned, I think I'm a 👎 as well, for the same reason as @kraih

**Comment by mche** [comment]
Okay, not so important/significant

**Pull request closed without merging**
