### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by s1037989**

### CODE REVIEW

**Comment by kraih** [comment]
Thanks, but i think a comma is where we have to draw the line for pull requests. :wink:

**Comment by s1037989** [comment]
Woops, sorry! Normally I just edit it online via Github when it's just a
typo. Doesn't that just create a PR too? Cuz you're not saying you don't
want simply typo fixes, correct?

**Comment by kraih** [comment]
If it's a bunch of typo fixes that's ok, but we can't do pull requests for every comma.

**Comment by s1037989** [comment]
No problem! I'll batch them up in the future! Which is somewhat awkward
because there are so few remaining...
:)

On Mar 4, 2016 11:38 PM, "Sebastian Riedel" <notifications@github.com>
wrote:
>
> If it's a bunch of typo fixes that's ok, but we can't do pull requests
for every comma.

**Pull request closed without merging**
