### PR TITLE
add swat command

### PR DESCRIPTION
**Pull request by melezhik**
HI @kraih !  [Swat](https://github.com/melezhik/swat) is a Simple Web Application Tests (API).
I found this interesting to generate swat tests for a existed mojo application using routes introspection embedded into mojo core. 

This is very first draft as swat could be integrated with, and could refined latter. 

Now swat command does this:

- walk through all available GET|POST mojo routes   and creates a swat test for every one
- when it is done one may run swat tests kept under ./swat directory 

---

Full documentation for SWAT is available here - https://github.com/melezhik/swat

Here is the example of swat command usage:

```

$ cat myapp.pl

#!/usr/bin/env perl
use Mojolicious::Lite;

# Documentation browser under "/perldoc"
plugin 'PODRenderer';

get '/' => sub {
  my $c = shift;
  $c->render(template => 'index');
};

get '/foo' => sub {
    my $c = shift;
    $c->render(text => 'Hello World!');
  };


post '/foo/bar' => sub {
 "OK"
};


app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
<h1>Welcome to the Mojolicious real-time web framework!</h1>
To learn more, you can browse through the documentation
<%= link_to 'here' => '/perldoc' %>.

@@ foobar.html.ep
% layout 'default';
% title 'Foo Bar';
Foo Bar

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body>

$ PERL5LIB=~/perl5/lib/perl5/ ./myapp.pl  swat
sorry, swat does not support * methods yet ... at Mojolicious/Command/swat.pm line 26, <DATA> line 43.
generate swat route for / ...
generate swat data for GET / ...
generate swat route for /foo ...
generate swat data for GET /foo ...
generate swat route for /foo/bar ...
generate swat data for POST /foo/bar ...

---
swat is ready to run: swat ./swat http://127.0.0.1:3000

$ PERL5LIB=~/perl5/lib/perl5/ ~/perl5/bin/morbo ./myapp.pl
Server available at http://127.0.0.1:3000

$ swat ./swat http://127.0.0.1:3000
/home/vagrant/.swat/reports/http://127.0.0.1:3000/00.t ...............
# start swat for http://127.0.0.1:3000// | is swat package 0
# swat version v0.1.19 | debug 0 | try num 2 | ignore http errors 0
ok 1 - successfull response from GET http://127.0.0.1:3000/
# data file: /home/vagrant/.swat/reports/http://127.0.0.1:3000///content.GET.txt
ok 2 - GET / returns 200 OK
1..2
ok
/home/vagrant/.swat/reports/http://127.0.0.1:3000/foo/00.t ...........
# start swat for http://127.0.0.1:3000//foo | is swat package 0
# swat version v0.1.19 | debug 0 | try num 2 | ignore http errors 0
ok 1 - successfull response from GET http://127.0.0.1:3000/foo
# data file: /home/vagrant/.swat/reports/http://127.0.0.1:3000//foo/content.GET.txt
ok 2 - GET /foo returns 200 OK
1..2
ok
/home/vagrant/.swat/reports/http://127.0.0.1:3000/foo/bar/00.post.t ..
# start swat for http://127.0.0.1:3000//foo/bar | is swat package 0
# swat version v0.1.19 | debug 0 | try num 2 | ignore http errors 0
ok 1 - successfull response from POST http://127.0.0.1:3000/foo/bar
# data file: /home/vagrant/.swat/reports/http://127.0.0.1:3000//foo/bar/content.POST.txt
ok 2 - POST /foo/bar returns 200 OK
1..2
ok
All tests successful.
Files=3, Tests=6,  0 wallclock secs ( 0.00 usr  0.01 sys +  0.04 cusr  0.01 csys =  0.06 CPU)
Result: PASS


```

### CODE REVIEW

**Comment by jhthorsen** [comment]
This looks interesting, but....

1. There's no tests
2. There's almost no documentation
3. I don't consider this to be a core Mojo feature

A :-1: from me

**Comment by Grinnz** [comment]
This looks to me like something that could easily be released as its own CPAN module. There are already many standalone Mojolicious::Command modules. As it is, even if tested and documented, I don't see a need for it in Mojo core, as Test::Mojo exists.

**Comment by melezhik** [comment]
| There's no tests
this is are scaffolds , or placeholdes for future tests, with minimal setup. "200 OK"

|    There's almost no documentation
I will added when we decides to go furher, as I said it is just a draft , I even had not to do it as MR, but it was the simplest way to express my idea

|    I don't consider this to be a core Mojo feature
Ok, is it possible still get an integration , wo including it into core. I am OK with this.

**Comment by kraih** [comment]
:-1: from me as well.

**Comment by melezhik** [comment]
| This looks to me like something that could easily be released as its own CPAN module.
it really does - http://search.cpan.org/perldoc?swat , as I talk about integration with existed mojo applications. Something like scaffolds in rails 

| Test::Mojo
I have not looked at this yet, probably I have to, I just want to make it clear that swat is for smoke tests

**Comment by jhthorsen** [comment]
What I meant about "No tests" is that there's no tests of _your_ code created in the mojo.git "t" directory.

@melezhik: @Grinnz meant actually releasing this PR as a perl dist on CPAN. We don't mind standalone CPAN modules in the Mojolicious::Command:: namespace.

https://metacpan.org/search?q=Mojolicious%3A%3ACommand%3A%3A&size=20&search_type=modules

**Comment by jberger** [comment]
Every time someone tries to auto-generate tests from routes, from my perspective, they skip the placeholders-in-routes problem. Sure its easy to generate tests when there are no placeholders but as soon as there are how do you effectively generate a useful (presumably set) of test(s)?

**Comment by melezhik** [comment]
@jhthorsen  I understood you. As it was intended as drat I did not accompanied my code with unit test under t/, I could do it when realize I can go ahead with my idea ...

**Comment by melezhik** [comment]
@jberger  it 's a scaffolds  , I cannot see a problem here. If a placeholder exists - just skip, no need to update it at all ( my current implementation dose not do that, but it is doable  ). use case is quite realistic. A developer starts an application,  let's say a dozens of routes, he needs ***smoke tests*** suite, this  might be achieved as simple  as running `./myapp.pl  swat`. it is fast and it is very useful.
Then he even add some more checks to generated swat tests ... Please follow swat doc and you will see how easy it is. So think about this command like fast way to bootstrap swat infrastructure for given mojo app ..

**Comment by jberger** [comment]
Your swat project itself seems to have no tests (unless using the module runs a bank of tests) and it seems that the application itself is bash not a portable tool. I wish you luck on your project but it is certainly too early to consider any integration into Mojolicious. That is officially a :-1: from me, so I will close this as a pull request (lost the vote by my count).

I recommend that you work on a plugin/command as @jhthorsen suggests and also perhaps write a blog post to describe how the workflow would look and how an example application would be tested.

**Comment by melezhik** [comment]
Guys thanks for feedback.  I really appreciate it. :)

@jberger 
I see some possible misunderstanding here - 

> seems that the application itself is bash not a portable tool. 

there is no need to port swat at all, it might be installed as ordinary cpan module and need not to be integrated with mojo. Please take a look at https://github.com/melezhik/swat

All I am trying  to say is that *it is possible to generate scaffolds for swat tests for given mojo application.
As the result of such an action swat tests will be created under ./swat or whatever directory, then a developer might start editing / or / running it right away with swat client ( no need to integrate it, it's external tools, cpan module  ). These  are smoke tests are ready to use. The "salt" is due to mojo introspection feature such a tests might be generated very easy.

Of course , if for some reasons you guys  think it should not be a mojo core command, it is ok. 
As I said, my MR initially was for sharing my idea, not as final working code.  We could even think about other ways to implement such a feature ... I just think that mojo and swat might take a benefits at some points ... 


> also perhaps write a blog post to describe how the workflow would look and how an example application would be tested.

Ok blog is doable, if it really helps I could  think about it.

**Comment by melezhik** [comment]
Hi @jberger  ! - This a informal description of possible swat/mojo cooperation - https://github.com/melezhik/Mojolicious-Command-Swat

**Pull request closed without merging**
