### PR TITLE
Use highlight.js instead of prettify for syntax coloring

### PR DESCRIPTION
**Pull request by dotandimet**
Note that the highlight.js Perl definition seems to tag less tokens than prettify, so I couldn't reproduce the current colors in full.

### CODE REVIEW

**Comment by kraih** [comment]
Thanks, the results look pretty good mostly, i'm just a little worried about the `<script>` block of our frontpage example.
w7ag8h9

**Comment by kraih** [comment]
This one is from the tutorial, so less critical, but would still be nice if the highlighting worked everywhere.
re

**Comment by kraih** [comment]
It might also be worth looking into [prism.js](http://prismjs.com/), i hear good things about it.

**Comment by dotandimet** [comment]
I just saw it mentioned in the Hacker News thread today, thinking about it.

**Comment by marcusramberg** [comment]
Yeah, I think based on https://github.com/isagalaev/highlight.js/pull/722 we should probably look for something else. Did you test prism, @dotandimet ?

**Comment by kraih** [comment]
I'm with @marcusramberg on that.

**Comment by kraih** [comment]
Closing this issue, since its "work in progress" status has caused some confusion.

**Pull request closed without merging**
