### PR TITLE
make max optional in num validation check

### PR DESCRIPTION
**Pull request by tim-2**
### Summary
make max value optional in num validation check

### Motivation
`num(1)` looks better than `num(1, 999)` or `num(1, 'inf')`

### CODE REVIEW

**Comment by kraih** [comment]
So, if `->num(2, undef)` becomes a feature, shouldn't `->num(undef, 2)` also be one?

**Comment by marcusramberg** [comment]
I'm positive to this feature but would like to see @kraih 's suggestion implemented for consistency.

**Comment by tim-2** [comment]
kraih: you're right. The number check could be done with `Scalar::Util::looks_like_number` to support negative numbers.

**Comment by Grinnz** [comment]
That is not at all what he suggested. And looks_like_number should never be used for validation.

**Comment by kraih** [comment]
@marcusramberg Technically, my suggestion seems to already be implemented, and just needs to be documented and tested.

**Comment by marcusramberg** [comment]
@tim-2 are you planning on updating this PR with tests and documentation for optional min value?

**Comment by marcusramberg** [comment]
I'm 👍 on accepting this PR now that the missing tests are added. Seems both cases are already documented.

**Comment by kraih** [comment]
Thanks, applied. In the future please squash your commits.

**Pull request merged**
