### PR TITLE
Improve punctuation

### PR DESCRIPTION
**Pull request by s1037989**

### CODE REVIEW

**Comment by zoffixznet** [comment]
:+1:

**Comment by kraih** [comment]
:-1: i'm afraid, because you've changed `application wide` to `application-wide` only in one place, which is inconsistent.

**Comment by kraih** [comment]
I've fixed the typo everywhere, since the punctuation changes need to be discussed separately. https://github.com/kraih/mojo/commit/8ea4618cf9a6c7c717b4062d282b353f6d2af086

**Comment by kraih** [comment]
We've talked about this on IRC, and there's many different opinions on how punctuation should look in that sentence. Not sure how to settle this.

**Comment by s1037989** [comment]
No problem!  Usually, FWIW, that's a sign (different opinions) that reducing the sentence to shorter and more sentences is in order.  Longer sentences can often be more efficient and clever, but readability (I think specifically in the case of this project) is likely the number one goal.  That might be just something worth keeping in mind, not necessarily striving for.

For uninterrupted clear readability, I do believe that "for example" should be offset with commas.  I think this is a case of "misplaced modifier".

"it allows you for example to customize" -> "it allows you to, for example, customize"

**Pull request closed without merging**
