### PR TITLE
Fix utf8 comments for test

### PR DESCRIPTION
**Pull request by rshadow**
### Summary
Fix utf8 comments for test

### Motivation
Compromise for `use utf8; use open ':std :utf8'` users and mojo.
Everybody gets what they want.

### References
#995
8fdf806ff56520bd79dfe0fe8fc24315918bfd37

### CODE REVIEW

**Comment by kraih** [comment]
Definitive 👎 from me, because this is what running the tests would look like. https://travis-ci.org/kraih/mojo/jobs/159861250

**Comment by rshadow** [comment]
You right. We need a big patch for migration mojo to utf8 support.

**Comment by kraih** [comment]
Please try to understand the problem completely before submitting more pull requests. It is very complicated and there will be no simple solution.

**Comment by rshadow** [comment]
OK. I go to IRC.

**Pull request closed without merging**
