### PR TITLE
Update Morbo.pm

### PR DESCRIPTION
**Pull request by Arseny-N**
Fixed typo.

### CODE REVIEW

**Comment by kraih** [comment]
I'm afraid that is not a typo.

**Comment by jhthorsen** [comment]
Would changing it to ```map { -f -r $_ ? $_ : files $_ }``` make it less confusing?

@Arseny-N: You can read more about ```_``` here: https://metacpan.org/pod/distribution/perl/pod/perlfunc.pod#X-FILEHANDLE (a couple of paragraphs down)

**Comment by jberger** [comment]
Funny I was about to reply that you needed a newer perl for that but ...
https://metacpan.org/pod/perl5100delta#Stacked-filetest-operators

**Comment by Arseny-N** [comment]
Oh! Thanks for the links.   @jhthorsen, yes it would be less confusing since it will not look like a typo, but if it will introduce some dependency on the perl version, then I think a  comment, containing a googlable phrase  would be good enough. 
After a second thought it seems stupid to comment a language feature, so ...

**Pull request closed without merging**
