### PR TITLE
n_map - eval on fixed size parcels of colllections

### PR DESCRIPTION
**Pull request by kiwiroy**
### Summary
Evaluate callback for, or call a method on, each `$n` elements in the collection and create a new collection from the results. The most basic use case would be tabling a flat collection.

### Motivation
This might be a useful addition to `Mojo::Collection`.

### References
none

### CODE REVIEW

**Comment by kraih** [comment]
Are there any common use cases?

**Comment by Grinnz** [comment]
Another name for a method like this could be 'bundle', similar to https://metacpan.org/pod/List::UtilsBy#bundle_by.

**Comment by jberger** [comment]
As to use cases, I could probably use it vs pairmap here: https://github.com/jberger/Mojo-Chrome/blob/8d0daab7972d6666e3a5534125815e1a30edaae6/lib/Mojo/Chrome.pm#L129 but I'm not sure that I actually would nor that that is enough.

IMHO I think this and other List::Utils and UtilsBy could be encouraged to start as Roles and if any prove extra popular/handy we can consider adding them to the core collection at that point.

**Comment by Grinnz** [comment]
I've put together a role to add most of the functions from List::UtilsBy. https://github.com/Grinnz/Mojo-Collection-Role-UtilsBy

**Comment by kraih** [comment]
Without good use cases i have to vote 👎. And i like the `UtilsBy` role.

**Comment by kiwiroy** [comment]
This started some awesome conversation and code from @Grinnz. I'm closing this as roles are the real solution here. Thanks.

**Comment by Grinnz** [comment]
The mentioned role has been released to CPAN. https://metacpan.org/pod/Mojo::Collection::Role::UtilsBy

**Pull request closed without merging**
