### PR TITLE
Morbo fixups

### PR DESCRIPTION
**Pull request by mohawk2**
### Summary
Current `t/mojo/morbo.t` has a bug: it does not test the local code, but the installed code instead.

### Motivation
Tests should test the correct thing. Also I have added a couple of doc snippets.

### References
I found this while having a look at making Morbo event-driven, as discussed on IRC.

### CODE REVIEW

**Comment by kraih** [comment]
Afraid this pull request has to be rejected because of the unexplained documentation changes. Making an environment variable part of the public API is a pretty big deal. I really don't like it when new features that require discussion are hidden in completely unrelated pull requests.

**Comment by kraih** [comment]
The proposed fix also appears to be wrong, everything works as expected for me already.

**Comment by mohawk2** [comment]
You're right about the module-finding thing. Proof: I switched to system Perl, which does not have Mojolicious installed. Works fine:

```shell
make && TEST_MORBO=1 MORBO_VERBOSE=1 prove -b t/mojo/morbo.t
```

Does not work, because `blib` only affects current process, instead of environment variable so not child processes:

```shell
make && TEST_MORBO=1 MORBO_VERBOSE=1 perl -Mblib t/mojo/morbo.t
```

Does work by setting relevant environment variables, including preserving value of `PERL5LIB` for `perlbrew`:

```shell
make && TEST_MORBO=1 MORBO_VERBOSE=1 PERL5LIB=blib/lib:blib/arch${PERL5LIB:+:$PERL5LIB} perl t/mojo/morbo.t
```

I would note that adding `-Mblib` to the command line in `morbo.t` *guarantees* it will use the `blib` version, which seems like a worthwhile thing to do. What do you think?

**Note**, running the above shows that the `MORBO_VERBOSE` output is swallowed, and I argue that this means the switching in `morbo.t` from `-|` to `|-` is the right thing to do. What do you think?

**Comment by kraih** [comment]
Afraid i do not follow your reasoning at all, everybody just uses `TEST_MORBO=1 prove -l t/mojo/morbo.t` and that works perfectly fine.

**Comment by mohawk2** [comment]
As discussed on IRC just now, it certainly will work. However, it swallows any stdout, such as that produced when `MORBO_VERBOSE` is true.

**Pull request closed without merging**
