### PR TITLE
Note about need to remove connection from the loop when you don't need it anymore

### PR DESCRIPTION
**Pull request by olegwtf**
This was non-obvious for me and I got this memory leak in my application.

### CODE REVIEW

**Comment by kraih** [comment]
:-1: This is not quite correct, a connection that times out or gets closed is automatically removed.

**Comment by olegwtf** [comment]
Ah, I see. Then may be add a note that loop will keep reference for a stream and it is not enough to forget received `$stream` to destroy it?

**Comment by olegwtf** [comment]
And finally I found cause of memory leak. I used unsubscribe on the stream: https://github.com/olegwtf/p5-Mojo-SMTP-Client/blob/d9715e9b0d39abb90a7d059881263c66a3d76aa0/lib/Mojo/SMTP/Client.pm#L282..L284 But `Mojo::IOLoop` setups non-documented event handlers which should remove stream from the loop when it will be closed. So, I still think this things should be cleared somehow in the documentation.

**Comment by kraih** [comment]
Keep i mind that `Mojo::IOLoop` is not an end user API, the documentation is intentionally vague so we can make changes for performance tuning and the like.

**Pull request closed without merging**
