### PR TITLE
create named variable within Mojo::Template

### PR DESCRIPTION
**Pull request by s1037989**
This leaves much to be desired, but I wanted to run my technique by you and get any comments from you.  Please let me know what I can do to make this PR acceptable.  Thanks!!

### CODE REVIEW

**Comment by kraih** [comment]
Making it work in `Mojo::Template` is not the hard part, you have to make it work for `Mojolicious::Plugin::EPRenderer` too.

**Comment by s1037989** [comment]
I'll look at that next if this is more or less acceptable?

**Comment by kraih** [comment]
I don't think there should be a stash in `Mojo::Template`, an attribute accessor containing a hash does the job just as well.

**Comment by kraih** [comment]
We generally don't do work in progress pull requests, if you want to discuss working branches you can do so on IRC or the mailing-list.

**Comment by s1037989** [comment]
OK no problem. How should I best share my code for discussion? Just link
you to my fork?

**Comment by kraih** [comment]
Yes.

**Comment by kraih** [comment]
I would expect something like this. https://gist.github.com/anonymous/f1066c1027e965dd4e5a

**Pull request closed without merging**
